/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConceptId = IDL.Text;
export const Order = IDL.Nat;
export const EntryId = IDL.Nat;
export const NotebookError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : EntryId,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : NotebookError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Concept = IDL.Record({
  'id' : ConceptId,
  'name' : IDL.Text,
  'page' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const NotebookEntryView = IDL.Record({
  'id' : EntryId,
  'title' : IDL.Text,
  'order' : Order,
  'body' : IDL.Text,
  'conceptId' : ConceptId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const Result = IDL.Variant({
  'ok' : NotebookEntryView,
  'err' : NotebookError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotebookEntry' : IDL.Func(
      [IDL.Text, IDL.Text, ConceptId, Order],
      [EntryId],
      [],
    ),
  'deleteNotebookEntry' : IDL.Func([EntryId], [Result_1], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConcepts' : IDL.Func([], [IDL.Vec(Concept)], ['query']),
  'listNotebookEntries' : IDL.Func([], [IDL.Vec(NotebookEntryView)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateNotebookEntry' : IDL.Func(
      [EntryId, IDL.Text, IDL.Text, ConceptId, Order],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConceptId = IDL.Text;
  const Order = IDL.Nat;
  const EntryId = IDL.Nat;
  const NotebookError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : EntryId,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : NotebookError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Concept = IDL.Record({
    'id' : ConceptId,
    'name' : IDL.Text,
    'page' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const NotebookEntryView = IDL.Record({
    'id' : EntryId,
    'title' : IDL.Text,
    'order' : Order,
    'body' : IDL.Text,
    'conceptId' : ConceptId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const Result = IDL.Variant({
    'ok' : NotebookEntryView,
    'err' : NotebookError,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotebookEntry' : IDL.Func(
        [IDL.Text, IDL.Text, ConceptId, Order],
        [EntryId],
        [],
      ),
    'deleteNotebookEntry' : IDL.Func([EntryId], [Result_1], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConcepts' : IDL.Func([], [IDL.Vec(Concept)], ['query']),
    'listNotebookEntries' : IDL.Func(
        [],
        [IDL.Vec(NotebookEntryView)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateNotebookEntry' : IDL.Func(
        [EntryId, IDL.Text, IDL.Text, ConceptId, Order],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };