/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Concept { 'id' : ConceptId, 'name' : string, 'page' : string }
export type ConceptId = string;
export type EntryId = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NotebookEntryView {
  'id' : EntryId,
  'title' : string,
  'order' : Order,
  'body' : string,
  'conceptId' : ConceptId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type NotebookError = { 'notAuthorized' : null } |
  { 'notFound' : EntryId };
export type Order = bigint;
export type Result = { 'ok' : NotebookEntryView } |
  { 'err' : NotebookError };
export type Result_1 = { 'ok' : null } |
  { 'err' : NotebookError };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a notebook entry owned by the signed-in caller.
   */
  'createNotebookEntry' : ActorMethod<
    [string, string, ConceptId, Order],
    EntryId
  >,
  /**
   * / Delete one of the caller's own entries.
   */
  'deleteNotebookEntry' : ActorMethod<[EntryId], Result_1>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / The backend's public API, as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / The canonical concept index: ids, display names, and owning page.
   */
  'listConcepts' : ActorMethod<[], Array<Concept>>,
  /**
   * / List the signed-in caller's own notebook entries.
   */
  'listNotebookEntries' : ActorMethod<[], Array<NotebookEntryView>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Update one of the caller's own entries.
   */
  'updateNotebookEntry' : ActorMethod<
    [EntryId, string, string, ConceptId, Order],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];